// Exportar todas las entidades
export * from './persona/persona.entity';
export * from './usuarios/usuario.entity';
export * from './alumnos/alumno.entity';
export * from './instructores/instructor.entity';
export * from './roles/rol.entity';
export * from './roles/persona-rol.entity';
export * from './catalogos/tipo-capacitacion.entity';
export * from './catalogos/modalidad-capacitacion.entity';
export * from './catalogos/tipo-pregunta.entity';
export * from './catalogos/tipo-material.entity';
export * from './capacitacion/capacitacion.entity';
export * from './materiales/material-capacitacion.entity';
export * from './secciones/seccion-capacitacion.entity';
export * from './lecciones/leccion.entity';
export * from './evaluaciones/evaluacion.entity';
export * from './evaluaciones/pregunta.entity';
export * from './evaluaciones/opcion-respuesta.entity';
export * from './inscripcion/inscripcion.entity';
export * from './progreso/progreso-leccion.entity';
export * from './evaluaciones/intento-evaluacion.entity';
export * from './evaluaciones/respuesta-estudiante.entity';
export * from './evaluaciones/respuesta-multiple.entity';
export * from './certificados/certificado.entity';
export * from './resenas/resena.entity';
// Nuevas entidades para cumplir requerimientos IPS Confianza
export * from './pagos/pago.entity';
export * from './auditoria/auditoria-certificado-retroactivo.entity';
export * from './alertas/configuracion-alerta.entity';
export * from './alertas/alerta-vencimiento.entity';
export * from './documentos/documento-legal.entity';
export * from './aceptaciones/aceptacion-politica.entity';
export * from './password-reset/password-reset-token.entity';
export * from './empresas/empresa.entity';
export * from './sesion/configuracion-sesion.entity';
export * from './certificate-formats/certificate-format.entity';
export * from './assistant/assistant-empresa-quota.entity';
export * from './assistant/assistant-empresa-usage.entity';
// export * from './logs/log-importacion.entity';
// export * from './logs/log-reporte.entity';
